"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { AnimatePresence, motion } from "framer-motion";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { portfolio } from "@/config/portfolio.config";

type Props={open:boolean;onOpenChange:(v:boolean)=>void};
export function CommandPalette({open,onOpenChange}:Props){const[q,setQ]=useState("");const items=useMemo(()=>[
 {label:"Buka About",href:"/#about",type:"Halaman"},{label:"Lihat Projects",href:"/projects",type:"Halaman"},{label:"Pengalaman",href:"/experience",type:"Halaman"},{label:"Resume",href:"/resume",type:"Dokumen"},{label:"Kontak",href:"/contact",type:"Aksi"},...portfolio.projects.map(p=>({label:p.title,href:`/projects/${p.slug}`,type:"Project"})),...portfolio.skills.map(s=>({label:s,href:"/#skills",type:"Skill"}))],[]);const filtered=items.filter(i=>(i.label+i.type).toLowerCase().includes(q.toLowerCase())).slice(0,9);
return <Dialog.Root open={open} onOpenChange={onOpenChange}><AnimatePresence>{open&&<Dialog.Portal forceMount><Dialog.Overlay asChild><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-40 bg-black/45 backdrop-blur-sm"/></Dialog.Overlay><Dialog.Content asChild><motion.div initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:.98}} className="fixed left-1/2 top-[12vh] z-50 w-[calc(100vw-2rem)] max-w-2xl -translate-x-1/2 overflow-hidden rounded-3xl border border-border bg-surface shadow-2xl"><Dialog.Title className="sr-only">Command palette</Dialog.Title><div className="flex items-center gap-3 border-b border-border px-5 py-4"><Search className="text-muted" size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari project, skill, halaman…" className="w-full bg-transparent text-base outline-none placeholder:text-muted"/></div><div className="max-h-[420px] overflow-auto p-2">{filtered.map(i=><a key={i.type+i.label} href={i.href} onClick={()=>onOpenChange(false)} className="flex items-center justify-between rounded-2xl px-4 py-3 transition hover:bg-card"><span>{i.label}</span><span className="text-xs text-muted">{i.type}</span></a>)}</div></motion.div></Dialog.Content></Dialog.Portal>}</AnimatePresence></Dialog.Root>}
