"use client";
import { motion } from "framer-motion";
import { Briefcase, Code2, FileText, Mail, Sparkles, UserRound, Search, Moon } from "lucide-react";
import { useTheme } from "next-themes";
import Link from "next/link";
import { useEffect, useState } from "react";
import { portfolio } from "@/config/portfolio.config";
import { Button } from "@/components/ui/button";
import { CommandPalette } from "./command-palette";

const apps=[{id:"about",label:"About",icon:UserRound},{id:"projects",label:"Projects",icon:Briefcase},{id:"experience",label:"Experience",icon:Sparkles},{id:"skills",label:"Skills",icon:Code2},{id:"resume",label:"Resume",icon:FileText},{id:"contact",label:"Contact",icon:Mail}];
export function OSShell({children}:{children:React.ReactNode}){const[cmd,setCmd]=useState(false);const{setTheme,theme}=useTheme();useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setCmd(true)}};addEventListener("keydown",h);return()=>removeEventListener("keydown",h)},[]);
return <div className="min-h-screen overflow-x-hidden bg-background text-foreground"><div className="os-grid fixed inset-0"/><aside className="fixed left-0 top-0 z-20 hidden h-screen w-20 border-r border-border bg-background/70 backdrop-blur-xl lg:block"><Link href="/" className="mx-auto mt-5 flex h-10 w-10 items-center justify-center rounded-2xl border border-border bg-card text-sm font-semibold">OS</Link><nav className="mt-8 flex flex-col items-center gap-3">{apps.map(a=><a key={a.id} href={`/#${a.id}`} aria-label={a.label} className="group flex h-11 w-11 items-center justify-center rounded-2xl text-muted transition hover:bg-card hover:text-foreground"><a.icon size={19}/></a>)}</nav></aside><header className="fixed inset-x-0 top-0 z-10 border-b border-border bg-background/65 backdrop-blur-xl lg:left-20"><div className="flex h-16 items-center justify-between px-4 lg:px-8"><div><p className="text-sm font-medium">{portfolio.name}</p><p className="text-xs text-muted">{portfolio.role}</p></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={()=>setCmd(true)}><Search size={15}/><span className="ml-2 hidden sm:inline">⌘K</span></Button><Button variant="ghost" size="sm" onClick={()=>setTheme(theme==="darker"?"light":theme==="light"?"dark":"darker")} aria-label="Ganti tema"><Moon size={16}/></Button></div></div></header><main className="relative pt-20 lg:pl-20">{children}</main><motion.nav initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} className="fixed bottom-4 left-1/2 z-30 flex -translate-x-1/2 gap-2 rounded-3xl border border-border bg-background/75 p-2 shadow-2xl backdrop-blur-xl">{apps.map(a=><a key={a.id} href={`/#${a.id}`} className="flex h-12 w-12 items-center justify-center rounded-2xl text-muted transition hover:bg-card hover:text-foreground sm:w-auto sm:px-4"><a.icon size={18}/><span className="ml-2 hidden text-sm sm:inline">{a.label}</span></a>)}</motion.nav><CommandPalette open={cmd} onOpenChange={setCmd}/></div>}
